### ISSUE TITLE
Package 'BMS' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Econometrics#11]
Package [BMS](https://CRAN.R-project.org/package=BMS) is currently listed in CRAN Task View [Econometrics](https://CRAN.R-project.org/view=Econometrics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by grantmcdermott** [comment]
@zeileis What's the protocol here? Should we just remove or (and?) reach out to the package authors?

I noticed that several other packages have been archived recently, especially in the "Panel data models" and "Instrumental variables" sections. (Although `ivpack` is now `ivmodel` AFAIK, which I'll update in the .md file.)

**Comment by zeileis** [comment]
Protocol: We need to decide whether it's worth to reach out to the original authors and motivate (or help) them to bring the package back to CRAN. Alternatively, we can decide that the package is not so important and just let it go from the task view.

In case of BMS I think it's very useful and I have already reached out twice to the authors (in April and in June) - and will do so again today.

As for the other recent archivals: I think for several of them it would be worth contacting the maintainers as well to see whether they would be willing to bring the packages back.

**Comment by zeileis** [comment]
Update regarding BMS and the other recently archived packages:

* `BMS`: I've contacted the authors again and also informed the maintainers of the Bayesian task view that also lists this package.
* `frm`: I contacted the author of as the package seemed reasonably substantial. The author still has some other packages on CRAN, even if there were no updates in recent years.
* `ivpack`: This wasn't updated since 2014 and much of the functionality seems to be available elsewhere now (e.g., clustered standard errors etc.). As you note there is `ivmodel` which has been co-authored by the `ivpack` authors. Hence I have removed `ivpack` from the task view, it would be great if you could add `ivmodel` (and possibly other IV packages).
* `ivfixed`/`ivpanel`/`Paneldata`/`wahc`: All of these packages were by the same author (Taha Zaghdoudi), relatively small and not updated since their initial release in 2014/15. As newer/better alternatives are available for most (or even all?) of the functionality is available, I have removed all of the packages from the task view.

**Comment by zeileis** [comment]
`BMS` is back on CRAN so I'm closing this issue.

Further remarks:

* `frm` will be resurrected on CRAN "later this year" by the maintainer. So I'm keeping it in the task view for now.
* The other packages (`ivpack`, `ivfixed`, `ivpanel`, `Paneldata`, and `wahc`) have all been removed from the task view.
* `ivmodel` can be added to the task view but we have the other issue open for this.
