### ISSUE TITLE
Add `hhi` package to the Econometrics TV?

### ISSUE THREAD

**Issue by pdwaggoner** [cran-task-views/Econometrics#13]
Hi - I am not sure if this package is appropriate for this TV, but given that the HHI measure was originally derived for explaining market competition, it seemed like there could be a fit. Its been downloaded over 23k times, and has been stably released since 2018. Feel free to check it out here: <https://github.com/pdwaggoner/hhi>

Let me know if this makes sense or not. Thanks for considering!

**Comment by zeileis** [comment]
Thanks for the suggestion. The topic is relevant to the Econometrics task view but I feel that the functionality is extremely limited. The Herfindahl index (or Herfindahl-Hirschman Index) is one of a bunch of inequality, concentration, and poverty measures in the `ineq` package which also support Herfindahl indexes with a parameter differing from 1.

There are many cases where we list alternative implementations next to each other but the `hhi()` function has less than 20 lines so I'm not sure how useful the addition is in this case.

I'm biased, though, because `ineq` is my package (my very first actually). So I leave the final decision to my co-maintainers.

Thanks nevertheless & best wishes!

**Comment by pdwaggoner** [comment]
Thanks for the reply. Certainly agreed on the limited functionality. This was also my first, originally developed to support my dissertation. Again, no worries if there isn't a fit. Thanks for considering

**Comment by tappek** [comment]
I was about so write something similar, so I second Achim's assessment.

Maybe we add Herfindahl-Hirschman Index to the description of `ineq` in the Task View? 
-> "some basic tools such as Lorenz curves, Pen's parade, the Gini coefficient, _Herfindahl-Hirschman index_ and many more."
So to make it more obvious `ineq` includes it.

**Comment by zeileis** [comment]
Good idea!

**Comment by pdwaggoner** [comment]
Sounds good. Thanks and good luck!

**Comment by tappek** [comment]
Thank your for taking the time to send the suggestion our way, @pdwaggoner. Shall you have more suggestions of other packages, we are happy to hear!
